Vagrant.configure("2") do |config|
  # Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "devops-api-vm"

  # Forward app port from VM -> host
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  # Sync project root into /vagrant inside VM
  config.vm.synced_folder "..", "/vagrant"

  # VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus   = 1
  end

  # Provision with Ansible (from your Ubuntu host)
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
